require("tkarner.options")
require("tkarner.keymaps")
require("tkarner.plugins")
require("tkarner.cmp")
require("tkarner.lsp")
require("tkarner.telescope")
require("tkarner.treesitter")
require("tkarner.autopairs")
require("tkarner.comment")
require("tkarner.gitsigns")
require("tkarner.nvim-tree")
require("tkarner.bufferline")
require("tkarner.toggleterm")
require("tkarner.lualine")
require("tkarner.whichkey")
require("tkarner.flutter-tools")
require("tkarner.todo-comments")

vim.cmd("colorscheme darkplus")
