require("tkarner.options")
require("tkarner.keymaps")
require("tkarner.plugins")
require("tkarner.cmp")
require("tkarner.lsp")
require("tkarner.dap")
require("tkarner.telescope")
require("tkarner.treesitter")
require("tkarner.autopairs")
require("tkarner.comment")
require("tkarner.gitsigns")
require("tkarner.nvim-tree")
require("tkarner.bufferline")
require("tkarner.lualine")
require("tkarner.whichkey")
require("tkarner.flutter-tools")
require("tkarner.todo-comments")
require("tkarner.gopher")
require("tkarner.nvim-test")
require("tkarner.nvim-scrollbar")

vim.cmd("colorscheme everforest")
